version: 1
disable_existing_loggers: False

formatters:
  default:
    # Use the local ColoredFormatter to add ANSI colors to the levelname
    (): data_commons_search.logging.ColoredFormatter
    format: "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
  access:
    (): data_commons_search.logging.ColoredFormatter
    format: "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: False
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: False
  uvicorn.access:
    level: WARNING
    handlers: [access]
    propagate: False
  httpx:
    level: WARNING
    handlers: [default]
    propagate: False
  mcp:
    level: WARNING
    handlers: [default]
    propagate: False
  # https://github.com/modelcontextprotocol/python-sdk/issues/1363
  mcp.server.streamable_http:
    level: CRITICAL
    handlers: [default]
    propagate: False
  opensearch:
    level: WARNING
    handlers: [default]
    propagate: False

root:
  level: INFO
  handlers: [default]
