name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: 📦 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      # - run: cargo fmt -- --check
      # - run: cargo clippy --all --all-targets --all-features
      - run: cargo build --release

  docker:
    name: 🐳 Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t data-commons-mcp .

      # - name: Test Docker image
      #   run: |
      #     CONTAINER_ID=$(docker run -d -p 8000:8000 data-commons-mcp)
      #     echo "Started container: $CONTAINER_ID"
      #     sleep 5
      #     docker stop $CONTAINER_ID
      #     docker rm $CONTAINER_ID
